#!/bin/bash
set -eEu
trap 'echo "$0: line $LINENO: exit code $?" >&2' ERR
log () { echo "$@" >&2; }
crash () { log "error: $@"; exit 1; }

_prog_path=$(readlink -e "${BASH_SOURCE[0]}")
_prog_name=$(basename "$_prog_path")
_prog_dir=$(dirname "$_prog_path")
_prog_args=()

which git >/dev/null 2>&1 || crash "git not found"
[ $# -eq 1 ] || crash "use: $_prog_name X.Y.Z"
[[ "$1" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] || crash "version [$1] not in format X.Y.Z"

echo "$1" >"$_prog_dir/VERSION"
echo VERSION
