#!/bin/bash
trap 'echo "exit code $?: LINENO=$LINENO BASH_LINENO=\"${BASH_LINENO[@]}\" FUNCNAME=\"${FUNCNAME[@]}\"" >&2' ERR
set -eEu -o pipefail
prog_name=$(basename "$0")

usage() {
    cat <<EOF
usage: $prog_name [-hv] [-d <dir>] [-c <ver_cmd>] [-f <ver_file>] [-r <proj_root>] [-o <out_file>] [-t <tag>]

Determine source tree version using the first method that works:
1. Change directory to <dir>, and run <ver_cmd> to describe its version.
2. If <ver_file> exists, read version from that file.
3. If the directory <proj_root> ends with "-[v]<num>.<num>[.<num>]", use the
suffix as version.
4. Failing all else, set version to "unknown".
Write the version as a single CPP define rule, defining the symbol <tag>. Send
the output to <out_file>. If <out_file> exists and already contains the correct
definition, do not update it.

The defaults are:
<dir>: .
<ver_cmd>: git describe --always --dirty --tags
<ver_file>: VERSION
<proj_root>: ..
<out_file>: stdout
<tag>: VERSION

Other options:
 -v : verbose messages
 -h : this help
EOF
}

dir=
version_command="git describe --always --dirty --tags"
version_file="VERSION"
project_root=..
output_file=
define_tag="VERSION"
verbose=

OPTIND=1
while getopts "d:c:f:r:o:t:vh" OPT "$@"; do
    case $OPT in
        d)
            dir=$OPTARG
            ;;
        c)
            version_command=$OPTARG
            ;;
        f)
            version_file=$OPTARG
            ;;
        r)
            project_root=$OPTARG
            ;;
        o)
            output_file=$OPTARG
            ;;
        t)
            define_tag=$OPTARG
            ;;
        v)
            verbose=1
            ;;
        h)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ "$verbose" ]; then
    exec {fd}>&2
else
    exec {fd}>/dev/null
fi

! [ "$dir" ] || cd "$dir"
version=$(
    (eval "$version_command" 2>/dev/null && echo "got version from: $version_command" >&$fd) ||
    (cat "$version_file" 2>/dev/null && echo "got version from file: $version_file" >&$fd) ||
    ([ -d "$project_root" ] &&
        name=$(basename "$(readlink -e "$project_root")") &&
        [[ "$name" =~ -v?[0-9]+.[0-9]+(.[0-9]+)?$ ]] &&
        echo "${name##*-}" &&
        echo "got version from project root folder" >&$fd) ||
    (echo "unknown" && echo "did not find version" >&$fd))
echo "found version=$version" >&$fd

if [ -r "$output_file" ]; then
    existing_version=$(awk -v tag="$define_tag" '$1=="#define"&&$2==tag {print $3}' <"$output_file" |
        sed 's/^"//;s/"$//')
    if [ "$existing_version" ]; then
        echo "found existing_version=$existing_version" >&$fd
        if [ "$version" = "$existing_version" ]; then
            echo "version up to date" >&$fd
            exit 0
        fi
    fi
fi

echo "#define ${define_tag} \"$version\"" |
if [ "$output_file" ]; then
    cat >"$output_file"
else
    cat
fi
